export const countryList = [
  {
    country: "Afghanistan",
    capital: "Kabul",
    abbreviation: "AF",
    flag: "🇦🇫",
    currency: "AFN",
  },
  {
    country: "Albania",
    capital: "Tirana",
    abbreviation: "AL",
    flag: "🇦🇱",
    currency: "ALL",
  },
  {
    country: "Algeria",
    capital: "Algiers",
    abbreviation: "DZ",
    flag: "🇩🇿",
    currency: "DZD",
  },
  {
    country: "Andorra",
    capital: "Andorra la Vella",
    abbreviation: "AD",
    flag: "🇦🇩",
    currency: "EUR",
  },
  {
    country: "Angola",
    capital: "Luanda",
    abbreviation: "AO",
    flag: "🇦🇴",
    currency: "AOA",
  },
  {
    country: "Antigua and Barbuda",
    capital: "St. John's",
    abbreviation: "AG",
    flag: "🇦🇬",
    currency: "XCD",
  },
  {
    country: "Argentina",
    capital: "Buenos Aires",
    abbreviation: "AR",
    flag: "🇦🇷",
    currency: "ARS",
  },
  {
    country: "Armenia",
    capital: "Yerevan",
    abbreviation: "AM",
    flag: "🇦🇲",
    currency: "AMD",
  },
  {
    country: "Australia",
    capital: "Canberra",
    abbreviation: "AU",
    flag: "🇦🇺",
    currency: "AUD",
  },
  {
    country: "Austria",
    capital: "Vienna",
    abbreviation: "AT",
    flag: "🇦🇹",
    currency: "EUR",
  },
  {
    country: "Azerbaijan",
    capital: "Baku",
    abbreviation: "AZ",
    flag: "🇦🇿",
    currency: "AZN",
  },
  {
    country: "Bahamas",
    capital: "Nassau",
    abbreviation: "BS",
    flag: "🇧🇸",
    currency: "BSD",
  },
  {
    country: "Bahrain",
    capital: "Manama",
    abbreviation: "BH",
    flag: "🇧🇭",
    currency: "BHD",
  },
  {
    country: "Bangladesh",
    capital: "Dhaka",
    abbreviation: "BD",
    flag: "🇧🇩",
    currency: "BDT",
  },
  {
    country: "Barbados",
    capital: "Bridgetown",
    abbreviation: "BB",
    flag: "🇧🇧",
    currency: "BBD",
  },
  {
    country: "Belarus",
    capital: "Minsk",
    abbreviation: "BY",
    flag: "🇧🇾",
    currency: "BYN",
  },
  {
    country: "Belgium",
    capital: "Brussels",
    abbreviation: "BE",
    flag: "🇧🇪",
    currency: "EUR",
  },
  {
    country: "Belize",
    capital: "Belmopan",
    abbreviation: "BZ",
    flag: "🇧🇿",
    currency: "BZD",
  },
  {
    country: "Benin",
    capital: "Porto-Novo",
    abbreviation: "BJ",
    flag: "🇧🇯",
    currency: "XOF",
  },
  {
    country: "Bhutan",
    capital: "Thimphu",
    abbreviation: "BT",
    flag: "🇧🇹",
    currency: "BTN",
  },
  {
    country: "Bolivia",
    capital: "Sucre",
    abbreviation: "BO",
    flag: "🇧🇴",
    currency: "BOB",
  },
  {
    country: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    abbreviation: "BA",
    flag: "🇧🇦",
    currency: "BAM",
  },
  {
    country: "Botswana",
    capital: "Gaborone",
    abbreviation: "BW",
    flag: "🇧🇼",
    currency: "BWP",
  },
  {
    country: "Brazil",
    capital: "Brasília",
    abbreviation: "BR",
    flag: "🇧🇷",
    currency: "BRL",
  },
  {
    country: "Brunei",
    capital: "Bandar Seri Begawan",
    abbreviation: "BN",
    flag: "🇧🇳",
    currency: "BND",
  },
  {
    country: "Bulgaria",
    capital: "Sofia",
    abbreviation: "BG",
    flag: "🇧🇬",
    currency: "BGN",
  },
  {
    country: "Burkina Faso",
    capital: "Ouagadougou",
    abbreviation: "BF",
    flag: "🇧🇫",
    currency: "XOF",
  },
  {
    country: "Burundi",
    capital: "Gitega",
    abbreviation: "BI",
    flag: "🇧🇮",
    currency: "BIF",
  },
  {
    country: "Cabo Verde",
    capital: "Praia",
    abbreviation: "CV",
    flag: "🇨🇻",
    currency: "CVE",
  },
  {
    country: "Cambodia",
    capital: "Phnom Penh",
    abbreviation: "KH",
    flag: "🇰🇭",
    currency: "KHR",
  },
  {
    country: "Cameroon",
    capital: "Yaoundé",
    abbreviation: "CM",
    flag: "🇨🇲",
    currency: "XAF",
  },
  {
    country: "Canada",
    capital: "Ottawa",
    abbreviation: "CA",
    flag: "🇨🇦",
    currency: "CAD",
  },
  {
    country: "Central African Republic",
    capital: "Bangui",
    abbreviation: "CF",
    flag: "🇨🇫",
    currency: "XAF",
  },
  {
    country: "Chad",
    capital: "N'Djamena",
    abbreviation: "TD",
    flag: "🇹🇩",
    currency: "XAF",
  },
  {
    country: "Chile",
    capital: "Santiago",
    abbreviation: "CL",
    flag: "🇨🇱",
    currency: "CLP",
  },
  {
    country: "China",
    capital: "Beijing",
    abbreviation: "CN",
    flag: "🇨🇳",
    currency: "CNY",
  },
  {
    country: "Colombia",
    capital: "Bogotá",
    abbreviation: "CO",
    flag: "🇨🇴",
    currency: "COP",
  },
  {
    country: "Comoros",
    capital: "Moroni",
    abbreviation: "KM",
    flag: "🇰🇲",
    currency: "KMF",
  },
  {
    country: "Congo (Congo-Brazzaville)",
    capital: "Brazzaville",
    abbreviation: "CG",
    flag: "🇨🇬",
    currency: "XAF",
  },
  {
    country: "Costa Rica",
    capital: "San José",
    abbreviation: "CR",
    flag: "🇨🇷",
    currency: "CRC",
  },
  {
    country: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    abbreviation: "CI",
    flag: "🇨🇮",
    currency: "XOF",
  },
  {
    country: "Croatia",
    capital: "Zagreb",
    abbreviation: "HR",
    flag: "🇭🇷",
    currency: "EUR",
  },
  {
    country: "Cuba",
    capital: "Havana",
    abbreviation: "CU",
    flag: "🇨🇺",
    currency: "CUP",
  },
  {
    country: "Cyprus",
    capital: "Nicosia",
    abbreviation: "CY",
    flag: "🇨🇾",
    currency: "EUR",
  },
  {
    country: "Czechia",
    capital: "Prague",
    abbreviation: "CZ",
    flag: "🇨🇿",
    currency: "CZK",
  },
  {
    country: "Democratic Republic of the Congo",
    capital: "Kinshasa",
    abbreviation: "CD",
    flag: "🇨🇩",
    currency: "CDF",
  },
  {
    country: "Denmark",
    capital: "Copenhagen",
    abbreviation: "DK",
    flag: "🇩🇰",
    currency: "DKK",
  },
  {
    country: "Djibouti",
    capital: "Djibouti",
    abbreviation: "DJ",
    flag: "🇩🇯",
    currency: "DJF",
  },
  {
    country: "Dominica",
    capital: "Roseau",
    abbreviation: "DM",
    flag: "🇩🇲",
    currency: "XCD",
  },
  {
    country: "Dominican Republic",
    capital: "Santo Domingo",
    abbreviation: "DO",
    flag: "🇩🇴",
    currency: "DOP",
  },
  {
    country: "Ecuador",
    capital: "Quito",
    abbreviation: "EC",
    flag: "🇪🇨",
    currency: "USD",
  },
  {
    country: "Egypt",
    capital: "Cairo",
    abbreviation: "EG",
    flag: "🇪🇬",
    currency: "EGP",
  },
  {
    country: "El Salvador",
    capital: "San Salvador",
    abbreviation: "SV",
    flag: "🇸🇻",
    currency: "USD",
  },
  {
    country: "Equatorial Guinea",
    capital: "Malabo",
    abbreviation: "GQ",
    flag: "🇬🇶",
    currency: "XAF",
  },
  {
    country: "Eritrea",
    capital: "Asmara",
    abbreviation: "ER",
    flag: "🇪🇷",
    currency: "ERN",
  },
  {
    country: "Estonia",
    capital: "Tallinn",
    abbreviation: "EE",
    flag: "🇪🇪",
    currency: "EUR",
  },
  {
    country: "Eswatini",
    capital: "Mbabane",
    abbreviation: "SZ",
    flag: "🇸🇿",
    currency: "SZL",
  },
  {
    country: "Ethiopia",
    capital: "Addis Ababa",
    abbreviation: "ET",
    flag: "🇪🇹",
    currency: "ETB",
  },
  {
    country: "Fiji",
    capital: "Suva",
    abbreviation: "FJ",
    flag: "🇫🇯",
    currency: "FJD",
  },
  {
    country: "Finland",
    capital: "Helsinki",
    abbreviation: "FI",
    flag: "🇫🇮",
    currency: "EUR",
  },
  {
    country: "France",
    capital: "Paris",
    abbreviation: "FR",
    flag: "🇫🇷",
    currency: "EUR",
  },
  {
    country: "Gabon",
    capital: "Libreville",
    abbreviation: "GA",
    flag: "🇬🇦",
    currency: "XAF",
  },
  {
    country: "Gambia",
    capital: "Banjul",
    abbreviation: "GM",
    flag: "🇬🇲",
    currency: "GMD",
  },
  {
    country: "Georgia",
    capital: "Tbilisi",
    abbreviation: "GE",
    flag: "🇬🇪",
    currency: "GEL",
  },
  {
    country: "Germany",
    capital: "Berlin",
    abbreviation: "DE",
    flag: "🇩🇪",
    currency: "EUR",
  },
  {
    country: "Ghana",
    capital: "Accra",
    abbreviation: "GH",
    flag: "🇬🇭",
    currency: "GHS",
  },
  {
    country: "Greece",
    capital: "Athens",
    abbreviation: "GR",
    flag: "🇬🇷",
    currency: "EUR",
  },
  {
    country: "Grenada",
    capital: "St. George's",
    abbreviation: "GD",
    flag: "🇬🇩",
    currency: "XCD",
  },
  {
    country: "Guatemala",
    capital: "Guatemala City",
    abbreviation: "GT",
    flag: "🇬🇹",
    currency: "GTQ",
  },
  {
    country: "Guinea",
    capital: "Conakry",
    abbreviation: "GN",
    flag: "🇬🇳",
    currency: "GNF",
  },
  {
    country: "Guinea-Bissau",
    capital: "Bissau",
    abbreviation: "GW",
    flag: "🇬🇼",
    currency: "XOF",
  },
  {
    country: "Guyana",
    capital: "Georgetown",
    abbreviation: "GY",
    flag: "🇬🇾",
    currency: "GYD",
  },
  {
    country: "Haiti",
    capital: "Port-au-Prince",
    abbreviation: "HT",
    flag: "🇭🇹",
    currency: "HTG",
  },
  {
    country: "Honduras",
    capital: "Tegucigalpa",
    abbreviation: "HN",
    flag: "🇭🇳",
    currency: "HNL",
  },
  {
    country: "Hungary",
    capital: "Budapest",
    abbreviation: "HU",
    flag: "🇭🇺",
    currency: "HUF",
  },
  {
    country: "Iceland",
    capital: "Reykjavik",
    abbreviation: "IS",
    flag: "🇮🇸",
    currency: "ISK",
  },
  {
    country: "India",
    capital: "New Delhi",
    abbreviation: "IN",
    flag: "🇮🇳",
    currency: "INR",
  },
  {
    country: "Indonesia",
    capital: "Jakarta",
    abbreviation: "ID",
    flag: "🇮🇩",
    currency: "IDR",
  },
  {
    country: "Iran",
    capital: "Tehran",
    abbreviation: "IR",
    flag: "🇮🇷",
    currency: "IRR",
  },
  {
    country: "Iraq",
    capital: "Baghdad",
    abbreviation: "IQ",
    flag: "🇮🇶",
    currency: "IQD",
  },
  {
    country: "Ireland",
    capital: "Dublin",
    abbreviation: "IE",
    flag: "🇮🇪",
    currency: "EUR",
  },
  {
    country: "Israel",
    capital: "Jerusalem",
    abbreviation: "IL",
    flag: "🇮🇱",
    currency: "ILS",
  },
  {
    country: "Italy",
    capital: "Rome",
    abbreviation: "IT",
    flag: "🇮🇹",
    currency: "EUR",
  },
  {
    country: "Jamaica",
    capital: "Kingston",
    abbreviation: "JM",
    flag: "🇯🇲",
    currency: "JMD",
  },
  {
    country: "Japan",
    capital: "Tokyo",
    abbreviation: "JP",
    flag: "🇯🇵",
    currency: "JPY",
  },
  {
    country: "Jordan",
    capital: "Amman",
    abbreviation: "JO",
    flag: "🇯🇴",
    currency: "JOD",
  },
  {
    country: "Kazakhstan",
    capital: "Astana",
    abbreviation: "KZ",
    flag: "🇰🇿",
    currency: "KZT",
  },
  {
    country: "Kenya",
    capital: "Nairobi",
    abbreviation: "KE",
    flag: "🇰🇪",
    currency: "KES",
  },
  {
    country: "Kiribati",
    capital: "South Tarawa",
    abbreviation: "KI",
    flag: "🇰🇮",
    currency: "AUD",
  },
  {
    country: "Korea (North)",
    capital: "Pyongyang",
    abbreviation: "KP",
    flag: "🇰🇵",
    currency: "KPW",
  },
  {
    country: "Korea (South)",
    capital: "Seoul",
    abbreviation: "KR",
    flag: "🇰🇷",
    currency: "KRW",
  },
  {
    country: "Kosovo",
    capital: "Pristina",
    abbreviation: "XK",
    flag: "🇽🇰",
    currency: "EUR",
  },
  {
    country: "Kuwait",
    capital: "Kuwait City",
    abbreviation: "KW",
    flag: "🇰🇼",
    currency: "KWD",
  },
  {
    country: "Kyrgyzstan",
    capital: "Bishkek",
    abbreviation: "KG",
    flag: "🇰🇬",
    currency: "KGS",
  },
  {
    country: "Laos",
    capital: "Vientiane",
    abbreviation: "LA",
    flag: "🇱🇦",
    currency: "LAK",
  },
  {
    country: "Latvia",
    capital: "Riga",
    abbreviation: "LV",
    flag: "🇱🇻",
    currency: "EUR",
  },
  {
    country: "Lebanon",
    capital: "Beirut",
    abbreviation: "LB",
    flag: "🇱🇧",
    currency: "LBP",
  },
  {
    country: "Lesotho",
    capital: "Maseru",
    abbreviation: "LS",
    flag: "🇱🇸",
    currency: "LSL",
  },
  {
    country: "Liberia",
    capital: "Monrovia",
    abbreviation: "LR",
    flag: "🇱🇷",
    currency: "LRD",
  },
  {
    country: "Libya",
    capital: "Tripoli",
    abbreviation: "LY",
    flag: "🇱🇾",
    currency: "LYD",
  },
  {
    country: "Liechtenstein",
    capital: "Vaduz",
    abbreviation: "LI",
    flag: "🇱🇮",
    currency: "CHF",
  },
  {
    country: "Lithuania",
    capital: "Vilnius",
    abbreviation: "LT",
    flag: "🇱🇹",
    currency: "EUR",
  },
  {
    country: "Luxembourg",
    capital: "Luxembourg City",
    abbreviation: "LU",
    flag: "🇱🇺",
    currency: "EUR",
  },
  {
    country: "Madagascar",
    capital: "Antananarivo",
    abbreviation: "MG",
    flag: "🇲🇬",
    currency: "MGA",
  },
  {
    country: "Malawi",
    capital: "Lilongwe",
    abbreviation: "MW",
    flag: "🇲🇼",
    currency: "MWK",
  },
  {
    country: "Malaysia",
    capital: "Kuala Lumpur",
    abbreviation: "MY",
    flag: "🇲🇾",
    currency: "MYR",
  },
  {
    country: "Maldives",
    capital: "Malé",
    abbreviation: "MV",
    flag: "🇲🇻",
    currency: "MVR",
  },
  {
    country: "Mali",
    capital: "Bamako",
    abbreviation: "ML",
    flag: "🇲🇱",
    currency: "XOF",
  },
  {
    country: "Malta",
    capital: "Valletta",
    abbreviation: "MT",
    flag: "🇲🇹",
    currency: "EUR",
  },
  {
    country: "Marshall Islands",
    capital: "Majuro",
    abbreviation: "MH",
    flag: "🇲🇭",
    currency: "USD",
  },
  {
    country: "Mauritania",
    capital: "Nouakchott",
    abbreviation: "MR",
    flag: "🇲🇷",
    currency: "MRU",
  },
  {
    country: "Mauritius",
    capital: "Port Louis",
    abbreviation: "MU",
    flag: "🇲🇺",
    currency: "MUR",
  },
  {
    country: "Mexico",
    capital: "Mexico City",
    abbreviation: "MX",
    flag: "🇲🇽",
    currency: "MXN",
  },
  {
    country: "Micronesia",
    capital: "Palikir",
    abbreviation: "FM",
    flag: "🇫🇲",
    currency: "USD",
  },
  {
    country: "Moldova",
    capital: "Chișinău",
    abbreviation: "MD",
    flag: "🇲🇩",
    currency: "MDL",
  },
  {
    country: "Monaco",
    capital: "Monaco",
    abbreviation: "MC",
    flag: "🇲🇨",
    currency: "EUR",
  },
  {
    country: "Mongolia",
    capital: "Ulaanbaatar",
    abbreviation: "MN",
    flag: "🇲🇳",
    currency: "MNT",
  },
  {
    country: "Montenegro",
    capital: "Podgorica",
    abbreviation: "ME",
    flag: "🇲🇪",
    currency: "EUR",
  },
  {
    country: "Morocco",
    capital: "Rabat",
    abbreviation: "MA",
    flag: "🇲🇦",
    currency: "MAD",
  },
  {
    country: "Mozambique",
    capital: "Maputo",
    abbreviation: "MZ",
    flag: "🇲🇿",
    currency: "MZN",
  },
  {
    country: "Myanmar",
    capital: "Naypyidaw",
    abbreviation: "MM",
    flag: "🇲🇲",
    currency: "MMK",
  },
  {
    country: "Namibia",
    capital: "Windhoek",
    abbreviation: "NA",
    flag: "🇳🇦",
    currency: "NAD",
  },
  {
    country: "Nauru",
    capital: "Yaren",
    abbreviation: "NR",
    flag: "🇳🇷",
    currency: "AUD",
  },
  {
    country: "Nepal",
    capital: "Kathmandu",
    abbreviation: "NP",
    flag: "🇳🇵",
    currency: "NPR",
  },
  {
    country: "Netherlands",
    capital: "Amsterdam",
    abbreviation: "NL",
    flag: "🇳🇱",
    currency: "EUR",
  },
  {
    country: "New Zealand",
    capital: "Wellington",
    abbreviation: "NZ",
    flag: "🇳🇿",
    currency: "NZD",
  },
  {
    country: "Nicaragua",
    capital: "Managua",
    abbreviation: "NI",
    flag: "🇳🇮",
    currency: "NIO",
  },
  {
    country: "Niger",
    capital: "Niamey",
    abbreviation: "NE",
    flag: "🇳🇪",
    currency: "XOF",
  },
  {
    country: "Nigeria",
    capital: "Abuja",
    abbreviation: "NG",
    flag: "🇳🇬",
    currency: "NGN",
  },
  {
    country: "North Macedonia",
    capital: "Skopje",
    abbreviation: "MK",
    flag: "🇲🇰",
    currency: "MKD",
  },
  {
    country: "Norway",
    capital: "Oslo",
    abbreviation: "NO",
    flag: "🇳🇴",
    currency: "NOK",
  },
  {
    country: "Oman",
    capital: "Muscat",
    abbreviation: "OM",
    flag: "🇴🇲",
    currency: "OMR",
  },
  {
    country: "Pakistan",
    capital: "Islamabad",
    abbreviation: "PK",
    flag: "🇵🇰",
    currency: "PKR",
  },
  {
    country: "Palau",
    capital: "Ngerulmud",
    abbreviation: "PW",
    flag: "🇵🇼",
    currency: "USD",
  },
  {
    country: "Palestine",
    capital: "Ramallah",
    abbreviation: "PS",
    flag: "🇵🇸",
    currency: "ILS",
  },
  {
    country: "Panama",
    capital: "Panama City",
    abbreviation: "PA",
    flag: "🇵🇦",
    currency: "PAB",
  },
  {
    country: "Papua New Guinea",
    capital: "Port Moresby",
    abbreviation: "PG",
    flag: "🇵🇬",
    currency: "PGK",
  },
  {
    country: "Paraguay",
    capital: "Asunción",
    abbreviation: "PY",
    flag: "🇵🇾",
    currency: "PYG",
  },
  {
    country: "Peru",
    capital: "Lima",
    abbreviation: "PE",
    flag: "🇵🇪",
    currency: "PEN",
  },
  {
    country: "Philippines",
    capital: "Manila",
    abbreviation: "PH",
    flag: "🇵🇭",
    currency: "PHP",
  },
  {
    country: "Poland",
    capital: "Warsaw",
    abbreviation: "PL",
    flag: "🇵🇱",
    currency: "PLN",
  },
  {
    country: "Portugal",
    capital: "Lisbon",
    abbreviation: "PT",
    flag: "🇵🇹",
    currency: "EUR",
  },
  {
    country: "Qatar",
    capital: "Doha",
    abbreviation: "QA",
    flag: "🇶🇦",
    currency: "QAR",
  },
  {
    country: "Romania",
    capital: "Bucharest",
    abbreviation: "RO",
    flag: "🇷🇴",
    currency: "RON",
  },
  {
    country: "Russia",
    capital: "Moscow",
    abbreviation: "RU",
    flag: "🇷🇺",
    currency: "RUB",
  },
  {
    country: "Rwanda",
    capital: "Kigali",
    abbreviation: "RW",
    flag: "🇷🇼",
    currency: "RWF",
  },
  {
    country: "Saint Kitts and Nevis",
    capital: "Basseterre",
    abbreviation: "KN",
    flag: "🇰🇳",
    currency: "XCD",
  },
  {
    country: "Saint Lucia",
    capital: "Castries",
    abbreviation: "LC",
    flag: "🇱🇨",
    currency: "XCD",
  },
  {
    country: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    abbreviation: "VC",
    flag: "🇻🇨",
    currency: "XCD",
  },
  {
    country: "Samoa",
    capital: "Apia",
    abbreviation: "WS",
    flag: "🇼🇸",
    currency: "WST",
  },
  {
    country: "San Marino",
    capital: "San Marino",
    abbreviation: "SM",
    flag: "🇸🇲",
    currency: "EUR",
  },
  {
    country: "Sao Tome and Principe",
    capital: "São Tomé",
    abbreviation: "ST",
    flag: "🇸🇹",
    currency: "STN",
  },
  {
    country: "Saudi Arabia",
    capital: "Riyadh",
    abbreviation: "SA",
    flag: "🇸🇦",
    currency: "SAR",
  },
  {
    country: "Senegal",
    capital: "Dakar",
    abbreviation: "SN",
    flag: "🇸🇳",
    currency: "XOF",
  },
  {
    country: "Serbia",
    capital: "Belgrade",
    abbreviation: "RS",
    flag: "🇷🇸",
    currency: "RSD",
  },
  {
    country: "Seychelles",
    capital: "Victoria",
    abbreviation: "SC",
    flag: "🇸🇨",
    currency: "SCR",
  },
  {
    country: "Sierra Leone",
    capital: "Freetown",
    abbreviation: "SL",
    flag: "🇸🇱",
    currency: "SLL",
  },
  {
    country: "Singapore",
    capital: "Singapore",
    abbreviation: "SG",
    flag: "🇸🇬",
    currency: "SGD",
  },
  {
    country: "Slovakia",
    capital: "Bratislava",
    abbreviation: "SK",
    flag: "🇸🇰",
    currency: "EUR",
  },
  {
    country: "Slovenia",
    capital: "Ljubljana",
    abbreviation: "SI",
    flag: "🇸🇮",
    currency: "EUR",
  },
  {
    country: "Solomon Islands",
    capital: "Honiara",
    abbreviation: "SB",
    flag: "🇸🇧",
    currency: "SBD",
  },
  {
    country: "Somalia",
    capital: "Mogadishu",
    abbreviation: "SO",
    flag: "🇸🇴",
    currency: "SOS",
  },
  {
    country: "South Africa",
    capital: "Pretoria",
    abbreviation: "ZA",
    flag: "🇿🇦",
    currency: "ZAR",
  },
  {
    country: "South Sudan",
    capital: "Juba",
    abbreviation: "SS",
    flag: "🇸🇸",
    currency: "SSP",
  },
  {
    country: "Spain",
    capital: "Madrid",
    abbreviation: "ES",
    flag: "🇪🇸",
    currency: "EUR",
  },
  {
    country: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    abbreviation: "LK",
    flag: "🇱🇰",
    currency: "LKR",
  },
  {
    country: "Sudan",
    capital: "Khartoum",
    abbreviation: "SD",
    flag: "🇸🇩",
    currency: "SDG",
  },
  {
    country: "Suriname",
    capital: "Paramaribo",
    abbreviation: "SR",
    flag: "🇸🇷",
    currency: "SRD",
  },
  {
    country: "Sweden",
    capital: "Stockholm",
    abbreviation: "SE",
    flag: "🇸🇪",
    currency: "SEK",
  },
  {
    country: "Switzerland",
    capital: "Bern",
    abbreviation: "CH",
    flag: "🇨🇭",
    currency: "CHF",
  },
  {
    country: "Syria",
    capital: "Damascus",
    abbreviation: "SY",
    flag: "🇸🇾",
    currency: "SYP",
  },
  {
    country: "Tajikistan",
    capital: "Dushanbe",
    abbreviation: "TJ",
    flag: "🇹🇯",
    currency: "TJS",
  },
  {
    country: "Tanzania",
    capital: "Dodoma",
    abbreviation: "TZ",
    flag: "🇹🇿",
    currency: "TZS",
  },
  {
    country: "Thailand",
    capital: "Bangkok",
    abbreviation: "TH",
    flag: "🇹🇭",
    currency: "THB",
  },
  {
    country: "Timor-Leste",
    capital: "Dili",
    abbreviation: "TL",
    flag: "🇹🇱",
    currency: "USD",
  },
  {
    country: "Togo",
    capital: "Lomé",
    abbreviation: "TG",
    flag: "🇹🇬",
    currency: "XOF",
  },
  {
    country: "Tonga",
    capital: "Nuku'alofa",
    abbreviation: "TO",
    flag: "🇹🇴",
    currency: "TOP",
  },
  {
    country: "Trinidad and Tobago",
    capital: "Port of Spain",
    abbreviation: "TT",
    flag: "🇹🇹",
    currency: "TTD",
  },
  {
    country: "Tunisia",
    capital: "Tunis",
    abbreviation: "TN",
    flag: "🇹🇳",
    currency: "TND",
  },
  {
    country: "Turkey",
    capital: "Ankara",
    abbreviation: "TR",
    flag: "🇹🇷",
    currency: "TRY",
  },
  {
    country: "Turkmenistan",
    capital: "Ashgabat",
    abbreviation: "TM",
    flag: "🇹🇲",
    currency: "TMT",
  },
  {
    country: "Tuvalu",
    capital: "Funafuti",
    abbreviation: "TV",
    flag: "🇹🇻",
    currency: "AUD",
  },
  {
    country: "Uganda",
    capital: "Kampala",
    abbreviation: "UG",
    flag: "🇺🇬",
    currency: "UGX",
  },
  {
    country: "Ukraine",
    capital: "Kyiv",
    abbreviation: "UA",
    flag: "🇺🇦",
    currency: "UAH",
  },
  {
    country: "United Arab Emirates",
    capital: "Abu Dhabi",
    abbreviation: "AE",
    flag: "🇦🇪",
    currency: "AED",
  },
  {
    country: "United Kingdom",
    capital: "London",
    abbreviation: "GB",
    flag: "🇬🇧",
    currency: "GBP",
  },
  {
    country: "United States of America",
    capital: "Washington, D.C.",
    abbreviation: "US",
    flag: "🇺🇸",
    currency: "USD",
  },
  {
    country: "Uruguay",
    capital: "Montevideo",
    abbreviation: "UY",
    flag: "🇺🇾",
    currency: "UYU",
  },
  {
    country: "Uzbekistan",
    capital: "Tashkent",
    abbreviation: "UZ",
    flag: "🇺🇿",
    currency: "UZS",
  },
  {
    country: "Vanuatu",
    capital: "Port Vila",
    abbreviation: "VU",
    flag: "🇻🇺",
    currency: "VUV",
  },
  {
    country: "Vatican City",
    capital: "Vatican City",
    abbreviation: "VA",
    flag: "🇻🇦",
    currency: "EUR",
  },
  {
    country: "Venezuela",
    capital: "Caracas",
    abbreviation: "VE",
    flag: "🇻🇪",
    currency: "VES",
  },
  {
    country: "Vietnam",
    capital: "Hanoi",
    abbreviation: "VN",
    flag: "🇻🇳",
    currency: "VND",
  },
  {
    country: "Yemen",
    capital: "Sana'a",
    abbreviation: "YE",
    flag: "🇾🇪",
    currency: "YER",
  },
  {
    country: "Zambia",
    capital: "Lusaka",
    abbreviation: "ZM",
    flag: "🇿🇲",
    currency: "ZMW",
  },
  {
    country: "Zimbabwe",
    capital: "Harare",
    abbreviation: "ZW",
    flag: "🇿🇼",
    currency: "ZWL",
  },
];
